import fs from 'fs';
import path from 'path';

interface VocabDef {
  id: number;
  hanzi: string;
  pinyin: string;
  correctAnswer: string;
  options: [string, string, string, string];
  explanation: string;
}

const rawVocab: VocabDef[] = [
  { id: 1, hanzi: "爱", pinyin: "ài", correctAnswer: "Yêu thích", options: ["Yêu thích", "Mua bán", "Nhìn ngắm", "Nói năng"], explanation: "爱 (ài) có nghĩa là yêu hoặc thích ai đó/cái gì đó (Ví dụ: 我爱你 - Tôi yêu bạn)." },
  { id: 2, hanzi: "八", pinyin: "bā", correctAnswer: "Số 8", options: ["Số 8", "Số 7", "Số 9", "Số 6"], explanation: "八 (bā) là số 8 trong tiếng Trung, đồng âm gần với từ 'phát' (phát tài)." },
  { id: 3, hanzi: "爸爸", pinyin: "bàba", correctAnswer: "Bố", options: ["Bố", "Mẹ", "Con trai", "Thầy giáo"], explanation: "爸爸 (bàba) nghĩa là bố/cha. Từ lặp lại âm nhẹ ở âm thứ 2." },
  { id: 4, hanzi: "杯子", pinyin: "bēizi", correctAnswer: "Cái cốc", options: ["Cái cốc", "Cái bàn", "Cái ghế", "Quyển sách"], explanation: "杯子 (bēizi) là cái cốc, cái ly dùng để uống nước hoặc trà." },
  { id: 5, hanzi: "北京", pinyin: "Běijīng", correctAnswer: "Bắc Kinh", options: ["Bắc Kinh", "Thượng Hải", "Quảng Châu", "Nam Kinh"], explanation: "北京 (Běijīng) là thủ đô của Trung Quốc (Bắc: phía bắc, Kinh: kinh đô)." },
  { id: 6, hanzi: "本", pinyin: "běn", correctAnswer: "Cuốn", options: ["Cuốn", "Cái", "Miếng", "Chiếc"], explanation: "本 (běn) là lượng từ dùng cho sách, vở, tạp chí (Ví dụ: 一本书 - một cuốn sách)." },
  { id: 7, hanzi: "不客气", pinyin: "bú kèqi", correctAnswer: "Đừng khách sáo", options: ["Đừng khách sáo", "Xin lỗi", "Cảm ơn", "Tạm biệt"], explanation: "不客气 (bú kèqi) dùng để đáp lại lời cảm ơn (谢谢) mang nghĩa đừng khách sáo." },
  { id: 8, hanzi: "不", pinyin: "bù", correctAnswer: "Không", options: ["Không", "Rất", "Đều", "Cũng"], explanation: "不 (bù) là phó từ phủ định, đứng trước động từ/tính từ (Ví dụ: 不好 - không tốt)." },
  { id: 9, hanzi: "菜", pinyin: "cài", correctAnswer: "Món ăn", options: ["Món ăn", "Cơm trắng", "Hoa quả", "Nước uống"], explanation: "菜 (cài) chỉ món ăn, thức ăn trên bàn hoặc các loại rau xanh." },
  { id: 10, hanzi: "茶", pinyin: "chá", correctAnswer: "Trà", options: ["Trà", "Nước", "Cơm", "Rượu"], explanation: "茶 (chá) là đồ uống trà truyền thống (Ví dụ: 喝茶 - uống trà)." },
  { id: 11, hanzi: "吃", pinyin: "chī", correctAnswer: "Ăn", options: ["Ăn", "Uống", "Ngủ", "Nói"], explanation: "吃 (chī) là hành động ăn thức ăn (Ví dụ: 吃饭 - ăn cơm)." },
  { id: 12, hanzi: "出租车", pinyin: "chūzūchē", correctAnswer: "Xe taxi", options: ["Xe taxi", "Máy bay", "Xe buýt", "Tàu hỏa"], explanation: "出租车 (chūzūchē) là xe taxi (xuất tô xa: xe cho thuê)." },
  { id: 13, hanzi: "打电话", pinyin: "dǎ diànhuà", correctAnswer: "Gọi điện thoại", options: ["Gọi điện thoại", "Xem vô tuyến", "Nghe bài hát", "Nói chuyện"], explanation: "打电话 (dǎ diànhuà) là gọi điện thoại (dǎ: đánh/bấm, diànhuà: điện thoại)." },
  { id: 14, hanzi: "大", pinyin: "dà", correctAnswer: "To lớn", options: ["To lớn", "Nhỏ bé", "Nhiều", "Ít"], explanation: "大 (dà) miêu tả kích thước lớn, to (đối lập với 小 - xiǎo)." },
  { id: 15, hanzi: "的", pinyin: "de", correctAnswer: "Của", options: ["Của", "Và", "Tại", "Đã"], explanation: "的 (de) kết nối định ngữ với trung tâm ngữ (Ví dụ: 我的书 - sách của tôi)." },
  { id: 16, hanzi: "点", pinyin: "diǎn", correctAnswer: "Giờ", options: ["Giờ", "Phút", "Năm", "Tháng"], explanation: "点 (diǎn) dùng để nói giờ trong ngày (Ví dụ: 八点 - 8 giờ) hoặc một chút (一点儿)." },
  { id: 17, hanzi: "电脑", pinyin: "diànnǎo", correctAnswer: "Máy tính", options: ["Máy tính", "Tivi", "Điện thoại", "Đồng hồ"], explanation: "电脑 (diànnǎo) nghĩa đen là 'não điện', tức máy vi tính." },
  { id: 18, hanzi: "电视", pinyin: "diànshì", correctAnswer: "Tivi", options: ["Tivi", "Phim ảnh", "Máy tính", "Điện thoại"], explanation: "电视 (diànshì) là ti-vi (truyền hình điện ảnh)." },
  { id: 19, hanzi: "电影", pinyin: "diànyǐng", correctAnswer: "Phim ảnh", options: ["Phim ảnh", "Tivi", "Sách báo", "Âm nhạc"], explanation: "电影 (diànyǐng) nghĩa là bộ phim chiếu rạp hoặc phim truyện." },
  { id: 20, hanzi: "东西", pinyin: "dōngxi", correctAnswer: "Đồ vật", options: ["Đồ vật", "Phương hướng", "Quần áo", "Thức ăn"], explanation: "东西 (dōngxi) chỉ đồ vật nói chung (Ví dụ: 买东西 - mua sắm đồ đạc)." },
  { id: 21, hanzi: "都", pinyin: "dōu", correctAnswer: "Đều", options: ["Đều", "Rất", "Không", "Cũng"], explanation: "都 (dōu) là phó từ chỉ tổng thể, mọi người/mọi thứ đều làm gì đó." },
  { id: 22, hanzi: "读", pinyin: "dú", correctAnswer: "Đọc", options: ["Đọc", "Viết", "Nói", "Nghe"], explanation: "读 (dú) là hành động đọc thành tiếng hoặc đọc sách (读书)." },
  { id: 23, hanzi: "对不起", pinyin: "duìbuqǐ", correctAnswer: "Xin lỗi", options: ["Xin lỗi", "Cảm ơn", "Không có chi", "Tạm biệt"], explanation: "对不起 (duìbuqǐ) dùng để bày tỏ lời xin lỗi một cách lịch sự." },
  { id: 24, hanzi: "多", pinyin: "duō", correctAnswer: "Nhiều", options: ["Nhiều", "Ít", "Lớn", "Nhỏ"], explanation: "多 (duō) chỉ số lượng phong phú, nhiều (đối lập với 少 - shǎo)." },
  { id: 25, hanzi: "多少", pinyin: "duōshao", correctAnswer: "Bao nhiêu", options: ["Bao nhiêu", "Mấy giờ", "Cái nào", "Ở đâu"], explanation: "多少 (duōshao) dùng để hỏi số lượng từ 10 trở lên hoặc hỏi giá cả." },
  { id: 26, hanzi: "儿子", pinyin: "érzi", correctAnswer: "Con trai", options: ["Con trai", "Con gái", "Người bố", "Học sinh"], explanation: "儿子 (érzi) là con trai trong quan hệ gia đình." },
  { id: 27, hanzi: "二", pinyin: "èr", correctAnswer: "Số 2", options: ["Số 2", "Số 1", "Số 3", "Số 4"], explanation: "二 (èr) là con số 2 trong tiếng Trung." },
  { id: 28, hanzi: "饭店", pinyin: "fàndiàn", correctAnswer: "Nhà hàng", options: ["Nhà hàng", "Bệnh viện", "Trường học", "Cửa hàng"], explanation: "饭店 (fàndiàn) là nơi ăn uống (nhà hàng) hoặc khách sạn lưu trú." },
  { id: 29, hanzi: "飞机", pinyin: "fēijī", correctAnswer: "Máy bay", options: ["Máy bay", "Xe taxi", "Tàu hỏa", "Xe buýt"], explanation: "飞机 (fēijī) nghĩa đen là 'phi cơ', phương tiện bay trên không." },
  { id: 30, hanzi: "分钟", pinyin: "fēnzhōng", correctAnswer: "Phút", options: ["Phút", "Giờ", "Giây", "Ngày"], explanation: "分钟 (fēnzhōng) chỉ khoảng thời gian tính bằng phút (Ví dụ: 五分钟 - 5 phút)." },
  { id: 31, hanzi: "高兴", pinyin: "gāoxìng", correctAnswer: "Vui vẻ", options: ["Vui vẻ", "Xinh đẹp", "Mệt mỏi", "Tức giận"], explanation: "高兴 (gāoxìng) miêu tả tâm trạng phấn khởi, vui mừng (很高兴认识你)." },
  { id: 32, hanzi: "个", pinyin: "gè", correctAnswer: "Cái", options: ["Cái", "Cuốn", "Miếng", "Chiếc"], explanation: "个 (gè) là lượng từ phổ biến nhất trong tiếng Trung (Ví dụ: 一个人 - một người)." },
  { id: 33, hanzi: "工作", pinyin: "gōngzuò", correctAnswer: "Làm việc", options: ["Làm việc", "Học tập", "Nghỉ ngơi", "Mua sắm"], explanation: "工作 (gōngzuò) vừa là danh từ (công việc) vừa là động từ (làm việc)." },
  { id: 34, hanzi: "狗", pinyin: "gǒu", correctAnswer: "Con chó", options: ["Con chó", "Con mèo", "Con chim", "Con cá"], explanation: "狗 (gǒu) chỉ loài chó (thú cưng, động vật nuôi)." },
  { id: 35, hanzi: "汉语", pinyin: "Hànyǔ", correctAnswer: "Tiếng Trung", options: ["Tiếng Trung", "Chữ Hán", "Trung Quốc", "Người Hoa"], explanation: "汉语 (Hànyǔ) là ngôn ngữ tiếng Hán/tiếng Trung Quốc." },
  { id: 36, hanzi: "好", pinyin: "hǎo", correctAnswer: "Tốt đẹp", options: ["Tốt đẹp", "Xấu tồi", "To lớn", "Nhỏ bé"], explanation: "好 (hǎo) mang ý nghĩa tốt lành, khỏe mạnh (Ví dụ: 你好 - chào bạn)." },
  { id: 37, hanzi: "号", pinyin: "hào", correctAnswer: "Ngày", options: ["Ngày", "Tháng", "Năm", "Tuần"], explanation: "号 (hào) dùng chỉ số nhà, số điện thoại hoặc ngày trong tháng (Ví dụ: 5号 - ngày 5)." },
  { id: 38, hanzi: "喝", pinyin: "hē", correctAnswer: "Uống", options: ["Uống", "Ăn", "Nói", "Nghe"], explanation: "喝 (hē) là động từ uống chất lỏng (Ví dụ: 喝水 - uống nước, 喝茶 - uống trà)." },
  { id: 39, hanzi: "和", pinyin: "hé", correctAnswer: "Và", options: ["Và", "Hoặc", "Nhưng", "Vì"], explanation: "和 (hé) là liên từ nối hai danh từ hoặc đại từ (Ví dụ: 我和他 - tôi và anh ấy)." },
  { id: 40, hanzi: "很", pinyin: "hěn", correctAnswer: "Rất", options: ["Rất", "Quá", "Đều", "Không"], explanation: "很 (hěn) là phó từ chỉ mức độ cao (Ví dụ: 很好 - rất tốt)." },
  { id: 41, hanzi: "后面", pinyin: "hòumiàn", correctAnswer: "Phía sau", options: ["Phía sau", "Phía trước", "Phía trong", "Phía ngoài"], explanation: "后面 (hòumiàn) là phương vị từ chỉ vị trí phía sau (đối lập với 前面)." },
  { id: 42, hanzi: "回", pinyin: "huí", correctAnswer: "Về", options: ["Về", "Đi", "Đến", "Ở"], explanation: "回 (huí) là động từ trở về nơi cũ (Ví dụ: 回家 - về nhà)." },
  { id: 43, hanzi: "会", pinyin: "huì", correctAnswer: "Biết làm", options: ["Biết làm", "Muốn làm", "Thích làm", "Phải làm"], explanation: "会 (huì) biểu thị kỹ năng có được qua học tập hoặc khả năng sẽ xảy ra trong tương lai." },
  { id: 44, hanzi: "几", pinyin: "jǐ", correctAnswer: "Mấy", options: ["Mấy", "Bao nhiêu", "Cái nào", "Ở đâu"], explanation: "几 (jǐ) dùng để hỏi số lượng nhỏ dưới 10 (Ví dụ: 几个人 - mấy người)." },
  { id: 45, hanzi: "家", pinyin: "jiā", correctAnswer: "Gia đình", options: ["Gia đình", "Trường học", "Cửa hàng", "Bệnh viện"], explanation: "家 (jiā) là mái ấm gia đình hoặc ngôi nhà nơi mình sinh sống." },
  { id: 46, hanzi: "叫", pinyin: "jiào", correctAnswer: "Tên là", options: ["Tên là", "Đi là", "Hỏi là", "Nghe là"], explanation: "叫 (jiào) dùng để giới thiệu tên gọi (Ví dụ: 你叫什么名字 - bạn tên là gì)." },
  { id: 47, hanzi: "今天", pinyin: "jīntiān", correctAnswer: "Hôm nay", options: ["Hôm nay", "Ngày mai", "Hôm qua", "Năm nay"], explanation: "今天 (jīntiān) chỉ ngày hiện tại." },
  { id: 48, hanzi: "九", pinyin: "jiǔ", correctAnswer: "Số 9", options: ["Số 9", "Số 8", "Số 7", "Số 6"], explanation: "九 (jiǔ) là con số 9 trong tiếng Trung." },
  { id: 49, hanzi: "开", pinyin: "kāi", correctAnswer: "Mở ra", options: ["Mở ra", "Đóng lại", "Dừng lại", "Đi về"], explanation: "开 (kāi) có nhiều nghĩa: 开门 (mở cửa), 开车 (lái xe), 开会 (họp)." },
  { id: 50, hanzi: "看", pinyin: "kàn", correctAnswer: "Nhìn xem", options: ["Nhìn xem", "Lắng nghe", "Nói chuyện", "Đọc sách"], explanation: "看 (kàn) là động từ thị giác (Ví dụ: 看书 - đọc sách, 看电视 - xem tivi)." },
  { id: 51, hanzi: "看见", pinyin: "kànjiàn", correctAnswer: "Nhìn thấy", options: ["Nhìn thấy", "Nghe thấy", "Gặp gỡ", "Nghĩ tới"], explanation: "看见 (kànjiàn) là bổ ngữ kết quả, biểu thị kết quả nhìn và thấy được đối tượng." },
  { id: 52, hanzi: "块", pinyin: "kuài", correctAnswer: "Đồng tiền", options: ["Đồng tiền", "Phút giây", "Quyển sách", "Chiếc xe"], explanation: "块 (kuài) dùng chỉ đơn vị tiền tệ khẩu ngữ (như tệ/đồng) hoặc một mảnh, một khối." },
  { id: 53, hanzi: "来", pinyin: "lái", correctAnswer: "Đến", options: ["Đến", "Đi", "Về", "Ở"], explanation: "来 (lái) chỉ chuyển động hướng về phía người nói (đối lập với 去 - đi xa)." },
  { id: 54, hanzi: "老师", pinyin: "lǎoshī", correctAnswer: "Thầy cô", options: ["Thầy cô", "Học trò", "Bác sĩ", "Bạn bè"], explanation: "老师 (lǎoshī) là danh xưng tôn kính dành cho người dạy học." },
  { id: 55, hanzi: "了", pinyin: "le", correctAnswer: "Rồi", options: ["Rồi", "Của", "Chăng", "Sao"], explanation: "了 (le) đặt sau động từ hoặc cuối câu để báo hiệu hành động đã xảy ra hoặc tình thế thay đổi." },
  { id: 56, hanzi: "冷", pinyin: "lěng", correctAnswer: "Lạnh", options: ["Lạnh", "Nóng", "Mát", "Ấm"], explanation: "冷 (lěng) miêu tả nhiệt độ thấp, thời tiết giá lạnh (đối lập với 热 - rè)." },
  { id: 57, hanzi: "里", pinyin: "lǐ", correctAnswer: "Bên trong", options: ["Bên trong", "Bên ngoài", "Bên trên", "Bên dưới"], explanation: "里 (lǐ) là từ chỉ vị trí phía trong (Ví dụ: 家里 - trong nhà, 学校里 - trong trường)." },
  { id: 58, hanzi: "六", pinyin: "liù", correctAnswer: "Số 6", options: ["Số 6", "Số 5", "Số 7", "Số 8"], explanation: "六 (liù) là con số 6 trong tiếng Trung." },
  { id: 59, hanzi: "吗", pinyin: "ma", correctAnswer: "Không", options: ["Không", "Có", "Đã", "Rồi"], explanation: "吗 (ma) đặt cuối câu trần thuật để biến câu thành câu hỏi yes/no (Ví dụ: 好吗 - tốt không?)." },
  { id: 60, hanzi: "妈妈", pinyin: "māma", correctAnswer: "Mẹ", options: ["Mẹ", "Bố", "Chị gái", "Con gái"], explanation: "妈妈 (māma) là tiếng gọi người mẹ thân thương." },
  { id: 61, hanzi: "买", pinyin: "mǎi", correctAnswer: "Mua", options: ["Mua", "Bán", "Ăn", "Xem"], explanation: "买 (mǎi) là hành động đổi tiền lấy hàng hóa (đối lập với 卖 - bán mang thanh 4)." },
  { id: 62, hanzi: "猫", pinyin: "māo", correctAnswer: "Con mèo", options: ["Con mèo", "Con chó", "Con chim", "Con cá"], explanation: "猫 (māo) là con mèo (thú cưng phát âm meo meo)." },
  { id: 63, hanzi: "没关系", pinyin: "méi guānxi", correctAnswer: "Không sao", options: ["Không sao", "Xin lỗi", "Cảm ơn", "Tạm biệt"], explanation: "没关系 (méi guānxi) thường dùng để đáp lại câu xin lỗi (对不起)." },
  { id: 64, hanzi: "没有", pinyin: "méiyǒu", correctAnswer: "Không có", options: ["Không có", "Đang có", "Có thể", "Cần có"], explanation: "没有 (méiyǒu) phủ định sự sở hữu hoặc hành động trong quá khứ (không dùng 不有)." },
  { id: 65, hanzi: "米饭", pinyin: "mǐfàn", correctAnswer: "Cơm", options: ["Cơm", "Mì", "Bánh", "Canh"], explanation: "米饭 (mǐfàn) là cơm nấu từ gạo (mǐ: gạo, fàn: thức ăn/cơm)." },
  { id: 66, hanzi: "名字", pinyin: "míngzi", correctAnswer: "Họ tên", options: ["Họ tên", "Tuổi tác", "Quê quán", "Nghề nghiệp"], explanation: "名字 (míngzi) nghĩa là tên gọi của một người hoặc sự vật." },
  { id: 67, hanzi: "明天", pinyin: "míngtiān", correctAnswer: "Ngày mai", options: ["Ngày mai", "Hôm nay", "Hôm qua", "Năm sau"], explanation: "明天 (míngtiān) là ngày kế tiếp ngày hôm nay (míng: sáng/rạng rỡ)." },
  { id: 68, hanzi: "哪", pinyin: "nǎ", correctAnswer: "Nào", options: ["Nào", "Kia", "Đây", "Đó"], explanation: "哪 (nǎ) là đại từ nghi vấn chỉ sự lựa chọn (Ví dụ: 哪个人 - người nào)." },
  { id: 69, hanzi: "哪儿", pinyin: "nǎr", correctAnswer: "Ở đâu", options: ["Ở đâu", "Ở kia", "Ở đây", "Khi nào"], explanation: "哪儿 (nǎr) là đại từ hỏi về nơi chốn, vị trí (bằng nghĩa với 哪里)." },
  { id: 70, hanzi: "那", pinyin: "nà", correctAnswer: "Kia", options: ["Kia", "Đây", "Nào", "Ai"], explanation: "那 (nà) dùng chỉ người hoặc vật ở xa người nói (đối lập với 这 - zhè)." },
  { id: 71, hanzi: "呢", pinyin: "ne", correctAnswer: "Thế còn", options: ["Thế còn", "Đúng không", "Tại sao", "Bao giờ"], explanation: "呢 (ne) dùng trong câu hỏi tỉnh lược (Ví dụ: 你呢？- Còn bạn thì sao?)." },
  { id: 72, hanzi: "能", pinyin: "néng", correctAnswer: "Có thể", options: ["Có thể", "Không thể", "Bắt buộc", "Muốn làm"], explanation: "能 (néng) biểu thị năng lực bẩm sinh hoặc điều kiện khách quan cho phép làm gì." },
  { id: 73, hanzi: "你", pinyin: "nǐ", correctAnswer: "Bạn", options: ["Bạn", "Tôi", "Anh ấy", "Chúng tôi"], explanation: "你 (nǐ) là đại từ nhân xưng ngôi thứ hai số ít." },
  { id: 74, hanzi: "年", pinyin: "nián", correctAnswer: "Năm", options: ["Năm", "Tháng", "Ngày", "Giờ"], explanation: "年 (nián) là đơn vị thời gian một năm (Ví dụ: 今年 - năm nay)." },
  { id: 75, hanzi: "女儿", pinyin: "nǚ'ér", correctAnswer: "Con gái", options: ["Con gái", "Con trai", "Người mẹ", "Chị gái"], explanation: "女儿 (nǚ'ér) chỉ con gái trong mối quan hệ gia đình cha mẹ - con cái." },
  { id: 76, hanzi: "朋友", pinyin: "péngyou", correctAnswer: "Bạn bè", options: ["Bạn bè", "Thầy giáo", "Học sinh", "Đồng nghiệp"], explanation: "朋友 (péngyou) là người bạn thân thiết, bằng hữu." },
  { id: 77, hanzi: "漂亮", pinyin: "piàoliang", correctAnswer: "Xinh đẹp", options: ["Xinh đẹp", "Xấu xí", "Thông minh", "Hiền lành"], explanation: "漂亮 (piàoliang) dùng khen ngợi ngoại hình người hoặc vẻ đẹp của sự vật." },
  { id: 78, hanzi: "苹果", pinyin: "píngguǒ", correctAnswer: "Quả táo", options: ["Quả táo", "Quả cam", "Quả chuối", "Dưa hấu"], explanation: "苹果 (píngguǒ) là quả táo tây ăn được." },
  { id: 79, hanzi: "七", pinyin: "qī", correctAnswer: "Số 7", options: ["Số 7", "Số 6", "Số 8", "Số 9"], explanation: "七 (qī) là con số 7 trong tiếng Trung." },
  { id: 80, hanzi: "前面", pinyin: "qiánmiàn", correctAnswer: "Phía trước", options: ["Phía trước", "Phía sau", "Bên trong", "Bên cạnh"], explanation: "前面 (qiánmiàn) là từ chỉ vị trí phía đằng trước (đối lập với 后面)." },
  { id: 81, hanzi: "钱", pinyin: "qián", correctAnswer: "Tiền bạc", options: ["Tiền bạc", "Thời gian", "Sách vở", "Quần áo"], explanation: "钱 (qián) nghĩa là tiền tệ dùng trong giao thương buôn bán (多少钱 - bao nhiêu tiền)." },
  { id: 82, hanzi: "请", pinyin: "qǐng", correctAnswer: "Mời", options: ["Mời", "Bảo", "Hỏi", "Nói"], explanation: "请 (qǐng) là từ lịch sự đặt đầu câu (Ví dụ: 请坐 - xin mời ngồi, 请进 - xin mời vào)." },
  { id: 83, hanzi: "去", pinyin: "qù", correctAnswer: "Đi", options: ["Đi", "Đến", "Về", "Ở"], explanation: "去 (qù) chỉ hành động rời khỏi vị trí hiện tại đi đến nơi khác." },
  { id: 84, hanzi: "热", pinyin: "rè", correctAnswer: "Nóng", options: ["Nóng", "Lạnh", "Ấm", "Mát"], explanation: "热 (rè) miêu tả thời tiết hoặc nhiệt độ cao, nóng bức (đối lập với 冷)." },
  { id: 85, hanzi: "人", pinyin: "rén", correctAnswer: "Con người", options: ["Con người", "Động vật", "Đồ vật", "Cây cối"], explanation: "人 (rén) chỉ nhân loại, con người nói chung (Ví dụ: 中国人 - người Trung Quốc)." },
  { id: 86, hanzi: "认识", pinyin: "rènshi", correctAnswer: "Quen biết", options: ["Quen biết", "Hiểu rõ", "Nhìn thấy", "Học tập"], explanation: "认识 (rènshi) nghĩa là quen biết ai đó hoặc nhận ra điều gì." },
  { id: 87, hanzi: "三", pinyin: "sān", correctAnswer: "Số 3", options: ["Số 3", "Số 4", "Số 2", "Số 5"], explanation: "三 (sān) là con số 3 trong tiếng Trung." },
  { id: 88, hanzi: "商店", pinyin: "shāngdiàn", correctAnswer: "Cửa hàng", options: ["Cửa hàng", "Bệnh viện", "Trường học", "Nhà hàng"], explanation: "商店 (shāngdiàn) là nơi mua bán hàng hóa, cửa hiệu tạp hóa." },
  { id: 89, hanzi: "上", pinyin: "shàng", correctAnswer: "Bên trên", options: ["Bên trên", "Bên dưới", "Bên trong", "Bên ngoài"], explanation: "上 (shàng) chỉ hướng đi lên trên hoặc vị trí ở trên bề mặt." },
  { id: 90, hanzi: "上午", pinyin: "shàngwǔ", correctAnswer: "Buổi sáng", options: ["Buổi sáng", "Buổi chiều", "Buổi trưa", "Buổi tối"], explanation: "上午 (shàngwǔ) là khoảng thời gian buổi sáng trước 12 giờ trưa." },
  { id: 91, hanzi: "少", pinyin: "shǎo", correctAnswer: "Ít", options: ["Ít", "Nhiều", "Nhỏ", "Lớn"], explanation: "少 (shǎo) mang nghĩa số lượng ít ỏi (đối lập với 多 - nhiều)." },
  { id: 92, hanzi: "谁", pinyin: "shéi", correctAnswer: "Ai", options: ["Ai", "Gì", "Đâu", "Sao"], explanation: "谁 (shéi) dùng để hỏi danh tính một người (Ví dụ: 他是谁 - anh ấy là ai?)." },
  { id: 93, hanzi: "什么", pinyin: "shénme", correctAnswer: "Cái gì", options: ["Cái gì", "Ở đâu", "Khi nào", "Ai đó"], explanation: "什么 (shénme) là đại từ nghi vấn dùng hỏi sự vật, hiện tượng (Ví dụ: 这是什么 - đây là cái gì?)." },
  { id: 94, hanzi: "十", pinyin: "shí", correctAnswer: "Số 10", options: ["Số 10", "Số 9", "Số 8", "Số 7"], explanation: "十 (shí) là con số 10 trong tiếng Trung." },
  { id: 95, hanzi: "时候", pinyin: "shíhou", correctAnswer: "Khi nào", options: ["Khi nào", "Ở đâu", "Bao nhiêu", "Thế nào"], explanation: "时候 (shíhou) dùng chỉ thời điểm hoặc trong cụm 什么时候 (khi nào, bao giờ)." },
  { id: 96, hanzi: "是", pinyin: "shì", correctAnswer: "Là", options: ["Là", "Có", "Không", "Đi"], explanation: "是 (shì) là động từ liên kết tương đương với 'to be' trong tiếng Anh (我是老师 - tôi là giáo viên)." },
  { id: 97, hanzi: "书", pinyin: "shū", correctAnswer: "Quyển sách", options: ["Quyển sách", "Cây bút", "Quyển vở", "Cái bàn"], explanation: "书 (shū) chỉ sách báo, tài liệu đọc." },
  { id: 98, hanzi: "水", pinyin: "shuǐ", correctAnswer: "Nước", options: ["Nước", "Trà", "Cơm", "Rượu"], explanation: "水 (shuǐ) chỉ nước uống hoặc chất lỏng nói chung (喝水 - uống nước)." },
  { id: 99, hanzi: "水果", pinyin: "shuǐguǒ", correctAnswer: "Trái cây", options: ["Trái cây", "Rau xanh", "Món ăn", "Nước ngọt"], explanation: "水果 (shuǐguǒ) chỉ các loại quả tươi ăn được như táo, cam, chuối." },
  { id: 100, hanzi: "睡觉", pinyin: "shuìjiào", correctAnswer: "Đi ngủ", options: ["Đi ngủ", "Thức dậy", "Ăn cơm", "Nghỉ ngơi"], explanation: "睡觉 (shuìjiào) là hành động đi ngủ nghỉ ngơi." },
  { id: 101, hanzi: "说", pinyin: "shuō", correctAnswer: "Nói", options: ["Nói", "Nghe", "Đọc", "Viết"], explanation: "说 (shuō) là phát ra lời nói (Ví dụ: 说话 - nói chuyện, 说汉语 - nói tiếng Trung)." },
  { id: 102, hanzi: "四", pinyin: "sì", correctAnswer: "Số 4", options: ["Số 4", "Số 3", "Số 5", "Số 6"], explanation: "四 (sì) là con số 4 trong tiếng Trung." },
  { id: 103, hanzi: "岁", pinyin: "suì", correctAnswer: "Tuổi", options: ["Tuổi", "Năm", "Tháng", "Ngày"], explanation: "岁 (suì) là từ chỉ độ tuổi của người (Ví dụ: 我二十岁 - tôi hai mươi tuổi)." },
  { id: 104, hanzi: "他", pinyin: "tā", correctAnswer: "Anh ấy", options: ["Anh ấy", "Cô ấy", "Nó", "Tôi"], explanation: "他 (tā) có bộ Nhân đứng (亻), chỉ người nam ngôi thứ ba số ít." },
  { id: 105, hanzi: "她", pinyin: "tā", correctAnswer: "Cô ấy", options: ["Cô ấy", "Anh ấy", "Chúng tôi", "Họ"], explanation: "她 (tā) có bộ Nữ (女), chỉ người nữ ngôi thứ ba số ít." },
  { id: 106, hanzi: "太", pinyin: "tài", correctAnswer: "Quá", options: ["Quá", "Rất", "Không", "Đều"], explanation: "太 (tài) biểu thị mức độ cực kỳ cao, hay gặp trong cấu trúc 太...了 (Ví dụ: 太好了 - tốt quá rồi)." },
  { id: 107, hanzi: "天气", pinyin: "tiānqì", correctAnswer: "Thời tiết", options: ["Thời tiết", "Thời gian", "Không khí", "Nhiệt độ"], explanation: "天气 (tiānqì) chỉ trạng thái thời tiết nắng, mưa, nóng, lạnh (Ví dụ: 今天天气很好)." },
  { id: 108, hanzi: "听", pinyin: "tīng", correctAnswer: "Lắng nghe", options: ["Lắng nghe", "Phát biểu", "Đọc sách", "Nhìn ngắm"], explanation: "听 (tīng) là hành động tiếp nhận âm thanh bằng tai (Ví dụ: 听音乐 - nghe nhạc)." },
  { id: 109, hanzi: "同学", pinyin: "tóngxué", correctAnswer: "Bạn học", options: ["Bạn học", "Thầy giáo", "Bác sĩ", "Hàng xóm"], explanation: "同学 (tóngxué) nghĩa là người học chung lớp, cùng trường." },
  { id: 110, hanzi: "喂", pinyin: "wèi", correctAnswer: "A-lô", options: ["A-lô", "Chào bạn", "Tạm biệt", "Cảm ơn"], explanation: "喂 (wèi) là thán từ dùng khi bắt máy điện thoại tương tự như 'a-lô'." },
  { id: 111, hanzi: "我", pinyin: "wǒ", correctAnswer: "Tôi", options: ["Tôi", "Bạn", "Anh ấy", "Chúng tôi"], explanation: "我 (wǒ) là đại từ nhân xưng ngôi thứ nhất số ít." },
  { id: 112, hanzi: "我们", pinyin: "wǒmen", correctAnswer: "Chúng tôi", options: ["Chúng tôi", "Các bạn", "Bọn họ", "Mọi người"], explanation: "Chúng tôi là đại từ nhân xưng ngôi thứ nhất số nhiều." },
  { id: 113, hanzi: "五", pinyin: "wǔ", correctAnswer: "Số 5", options: ["Số 5", "Số 4", "Số 6", "Số 7"], explanation: "五 (wǔ) là con số 5 trong tiếng Trung." },
  { id: 114, hanzi: "喜欢", pinyin: "xǐhuan", correctAnswer: "Yêu thích", options: ["Yêu thích", "Chán ghét", "Muốn có", "Hiểu biết"], explanation: "喜欢 (xǐhuan) biểu thị sự yêu thích đối với người hoặc điều gì (Ví dụ: 我喜欢苹果)." },
  { id: 115, hanzi: "下", pinyin: "xià", correctAnswer: "Bên dưới", options: ["Bên dưới", "Bên trên", "Bên trong", "Bên ngoài"], explanation: "下 (xià) chỉ hướng đi xuống hoặc vị trí ở phía dưới (đối lập với 上)." },
  { id: 116, hanzi: "下午", pinyin: "xiàwǔ", correctAnswer: "Buổi chiều", options: ["Buổi chiều", "Buổi sáng", "Buổi trưa", "Buổi tối"], explanation: "下午 (xiàwǔ) là khoảng thời gian buổi chiều sau 12 giờ trưa." },
  { id: 117, hanzi: "下雨", pinyin: "xiàyǔ", correctAnswer: "Trời mưa", options: ["Trời mưa", "Trời nắng", "Trời rét", "Có gió"], explanation: "下雨 (xiàyǔ) miêu tả hiện tượng mưa rơi từ bầu trời (雨: mưa)." },
  { id: 118, hanzi: "先生", pinyin: "xiānsheng", correctAnswer: "Quý ông", options: ["Quý ông", "Quý cô", "Bác sĩ", "Thầy giáo"], explanation: "先生 (xiānsheng) là danh xưng lịch sự dành cho phái nam (Ví dụ: 王先生 - ông Vương)." },
  { id: 119, hanzi: "现在", pinyin: "xiànzài", correctAnswer: "Bây giờ", options: ["Bây giờ", "Hôm nay", "Lúc trước", "Sau này"], explanation: "现在 (xiànzài) chỉ thời điểm ngay lúc này (Ví dụ: 现在几点 - bây giờ là mấy giờ?)." },
  { id: 120, hanzi: "想", pinyin: "xiǎng", correctAnswer: "Muốn", options: ["Muốn", "Làm", "Xem", "Ăn"], explanation: "想 (xiǎng) biểu thị suy nghĩ, ước muốn làm điều gì đó hoặc nhớ nhung người khác." },
  { id: 121, hanzi: "小", pinyin: "xiǎo", correctAnswer: "Nhỏ bé", options: ["Nhỏ bé", "To lớn", "Nhiều", "Ít"], explanation: "小 (xiǎo) miêu tả kích thước nhỏ bé (đối lập với 大 - to lớn)." },
  { id: 122, hanzi: "小姐", pinyin: "xiǎojiě", correctAnswer: "Cô gái", options: ["Cô gái", "Quý ông", "Người mẹ", "Con gái"], explanation: "小姐 (xiǎojiě) là danh xưng lịch sự dành cho phụ nữ trẻ tuổi (Ví dụ: 李小姐 - cô Lý)." },
  { id: 123, hanzi: "些", pinyin: "xiē", correctAnswer: "Một vài", options: ["Một vài", "Tất cả", "Rất nhiều", "Một cái"], explanation: "些 (xiē) là lượng từ biểu thị số lượng không xác định (Ví dụ: 这些 - những cái này, 一些 - một ít)." },
  { id: 124, hanzi: "写", pinyin: "xiě", correctAnswer: "Viết chữ", options: ["Viết chữ", "Đọc sách", "Nghe nhạc", "Hội họa"], explanation: "写 (xiě) là hành động cầm bút ghi chữ (Ví dụ: 写字 - viết chữ, 写汉字 - viết chữ Hán)." },
  { id: 125, hanzi: "谢谢", pinyin: "xièxie", correctAnswer: "Cảm ơn", options: ["Cảm ơn", "Xin lỗi", "Tạm biệt", "Đừng ngại"], explanation: "谢谢 (xièxie) là câu nói cảm ơn quen thuộc khi nhận được sự giúp đỡ." },
  { id: 126, hanzi: "星期", pinyin: "xīngqī", correctAnswer: "Tuần lễ", options: ["Tuần lễ", "Tháng", "Năm", "Ngày"], explanation: "星期 (xīngqī) nghĩa là tuần lễ hoặc dùng để nói thứ (Ví dụ: 星期一 - thứ Hai)." },
  { id: 127, hanzi: "学生", pinyin: "xuésheng", correctAnswer: "Học sinh", options: ["Học sinh", "Giáo viên", "Bác sĩ", "Bạn bè"], explanation: "学生 (xuésheng) chỉ người đang học tập tại trường lớp." },
  { id: 128, hanzi: "学习", pinyin: "xuéxí", correctAnswer: "Học tập", options: ["Học tập", "Làm việc", "Nghỉ ngơi", "Mua sắm"], explanation: "学习 (xuéxí) là động từ học hỏi kiến thức, kỹ năng (Ví dụ: 学习汉语 - học tiếng Trung)." },
  { id: 129, hanzi: "学校", pinyin: "xuéxiào", correctAnswer: "Trường học", options: ["Trường học", "Bệnh viện", "Cửa hàng", "Nhà hàng"], explanation: "学校 (xuéxiào) là cơ sở giáo dục, ngôi trường nơi học sinh theo học." },
  { id: 130, hanzi: "一", pinyin: "yī", correctAnswer: "Số 1", options: ["Số 1", "Số 2", "Số 3", "Số 10"], explanation: "一 (yī) là con số 1 trong tiếng Trung." },
  { id: 131, hanzi: "一点儿", pinyin: "yìdiǎnr", correctAnswer: "Một chút", options: ["Một chút", "Rất nhiều", "Bao nhiêu", "Tất cả"], explanation: "一点儿 (yìdiǎnr) đứng trước danh từ biểu thị số lượng nhỏ (Ví dụ: 吃一点儿 - ăn một chút)." },
  { id: 132, hanzi: "医生", pinyin: "yīshēng", correctAnswer: "Bác sĩ", options: ["Bác sĩ", "Giáo viên", "Học sinh", "Y tá"], explanation: "医生 (yīshēng) là người làm nghề chữa bệnh (y sinh)." },
  { id: 133, hanzi: "医院", pinyin: "yīyuàn", correctAnswer: "Bệnh viện", options: ["Bệnh viện", "Trường học", "Cửa hàng", "Nhà thuốc"], explanation: "医院 (yīyuàn) là cơ sở khám và chữa bệnh (y viện)." },
  { id: 134, hanzi: "衣服", pinyin: "yīfu", correctAnswer: "Quần áo", options: ["Quần áo", "Giày dép", "Túi xách", "Mũ nón"], explanation: "衣服 (yīfu) chỉ quần áo may mặc mặc trên người." },
  { id: 135, hanzi: "椅子", pinyin: "yǐzi", correctAnswer: "Cái ghế", options: ["Cái ghế", "Cái bàn", "Cái giường", "Cái cốc"], explanation: "椅子 (yǐzi) là đồ dùng nội thất để ngồi." },
  { id: 136, hanzi: "有", pinyin: "yǒu", correctAnswer: "Có", options: ["Có", "Không", "Là", "Ở"], explanation: "有 (yǒu) biểu thị sự sở hữu hoặc tồn tại (Ví dụ: 我有一本书 - tôi có một cuốn sách)." },
  { id: 137, hanzi: "月", pinyin: "yuè", correctAnswer: "Tháng", options: ["Tháng", "Năm", "Ngày", "Tuần"], explanation: "月 (yuè) dùng chỉ các tháng trong năm (Ví dụ: 一月 - tháng 1) hoặc mặt trăng." },
  { id: 138, hanzi: "再见", pinyin: "zàijiàn", correctAnswer: "Tạm biệt", options: ["Tạm biệt", "Xin chào", "Cảm ơn", "Đừng ngại"], explanation: "再见 (zàijiàn) nghĩa đen là 'gặp lại lần sau', lời chào khi chia tay." },
  { id: 139, hanzi: "在", pinyin: "zài", correctAnswer: "Ở tại", options: ["Ở tại", "Đi đến", "Trở về", "Rời khỏi"], explanation: "在 (zài) chỉ vị trí nơi chốn (我在家 - tôi ở nhà) hoặc phó từ chỉ hành động đang diễn ra." },
  { id: 140, hanzi: "怎么", pinyin: "zěnme", correctAnswer: "Làm sao", options: ["Làm sao", "Ở đâu", "Bao nhiêu", "Cái gì"], explanation: "怎么 (zěnme) dùng hỏi phương thức hành động (怎么去) hoặc nguyên do (怎么了)." },
  { id: 141, hanzi: "怎么样", pinyin: "zěnmeyàng", correctAnswer: "Thế nào", options: ["Thế nào", "Bao nhiêu", "Ở đâu", "Làm gì"], explanation: "怎么样 (zěnmeyàng) dùng hỏi tình hình hoặc trưng cầu ý kiến người khác." },
  { id: 142, hanzi: "这", pinyin: "zhè", correctAnswer: "Đây", options: ["Đây", "Đó", "Nào", "Ai"], explanation: "这 (zhè) dùng để chỉ người hoặc vật ở gần vị trí người nói (đối lập với 那)." },
  { id: 143, hanzi: "中国", pinyin: "Zhōngguó", correctAnswer: "Trung Quốc", options: ["Trung Quốc", "Bắc Kinh", "Việt Nam", "Nước Mỹ"], explanation: "中国 (Zhōngguó) là tên quốc gia Trung Quốc." },
  { id: 144, hanzi: "中午", pinyin: "zhōngwǔ", correctAnswer: "Buổi trưa", options: ["Buổi trưa", "Buổi sáng", "Buổi chiều", "Buổi tối"], explanation: "中午 (zhōngwǔ) là thời điểm chính giữa ngày (11h30 - 13h00)." },
  { id: 145, hanzi: "住", pinyin: "zhù", correctAnswer: "Cư trú", options: ["Cư trú", "Rời đi", "Làm việc", "Học tập"], explanation: "住 (zhù) là động từ chỉ việc sinh sống, cư ngụ tại một địa điểm (Ví dụ: 住北京)." },
  { id: 146, hanzi: "桌子", pinyin: "zhuōzi", correctAnswer: "Cái bàn", options: ["Cái bàn", "Cái ghế", "Cái giường", "Cái cốc"], explanation: "桌子 (zhuōzi) là đồ gia dụng cái bàn (đặt sách, đồ ăn lên mặt bàn)." },
  { id: 147, hanzi: "字", pinyin: "zì", correctAnswer: "Chữ viết", options: ["Chữ viết", "Quyển sách", "Tiếng nói", "Tên gọi"], explanation: "字 (zì) chỉ mặt chữ hoặc ký tự (Ví dụ: 汉字 - chữ Hán, 写字 - viết chữ)." },
  { id: 148, hanzi: "昨天", pinyin: "zuótiān", correctAnswer: "Hôm qua", options: ["Hôm qua", "Hôm nay", "Ngày mai", "Năm ngoái"], explanation: "昨天 (zuótiān) là ngày liền trước ngày hôm nay (ngày đã qua)." },
  { id: 149, hanzi: "做", pinyin: "zuò", correctAnswer: "Làm", options: ["Làm", "Ngồi", "Đi", "Xem"], explanation: "做 (zuò) là động từ hành động chỉ việc làm ra cái gì đó (Ví dụ: 做饭 - nấu cơm, 做工作)." },
  { id: 150, hanzi: "坐", pinyin: "zuò", correctAnswer: "Ngồi", options: ["Ngồi", "Đứng", "Chạy", "Nằm"], explanation: "坐 (zuò) nghĩa là ngồi xuống (请坐) hoặc đi bằng một phương tiện giao thông (坐飞机)." }
];

export function buildData() {
  const formattedQuestions = rawVocab.map(v => ({
    id: v.id,
    hanzi: v.hanzi,
    pinyin: v.pinyin,
    question: v.hanzi + " — " + v.pinyin + " nghĩa là gì?",
    options: v.options,
    correctAnswer: v.correctAnswer,
    explanation: v.explanation,
  }));

  const code = "import { QuizQuestion } from '@/types/quiz';\n\nexport const HSK1_VOCAB_DATA: QuizQuestion[] = " +
    JSON.stringify(formattedQuestions, null, 2) + ";\n";

  const outputPath = path.resolve(process.cwd(), 'data/hsk1-data.ts');
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, code, 'utf-8');
  console.log("Generated " + rawVocab.length + " vocabulary questions at " + outputPath);
}

buildData();
